### ISSUE TITLE
 Unauthorized, invalid sign

### ISSUE THREAD

**Issue by william-swl** [qiushaocloud/site-counter#1]
您好，docker自建遇到`[ERROR] API - Unauthorized, invalid sign`错误。无论是编辑container内的`/root/site-counter/web-js/.env`，还是直接在`docker-compose.yml`中指定`environment`参数，都无法解决

我指定了`YOUR_SERVER_HOST`和`API_SIGN_SECRET_KEY`环境变量，分别是我docker部署的`site-counter`域名和设置的key，与前端引入的`qiushaocloud_sitecounter_api_host`、`QIUSHAOCLOUD_SITE_COUNTER_API_SIGN_SECRET_KEY`一致

`YOUR_SERVER_HOST`是我用nginx转发到的子域名，直接访问可以返回

```
site counter server runing
reqInfo:{"ip":"::ffff:172.19.0.5","method":"get","query":{},"fields":{}}
author blog: https://www.qiushaocloud.top
```

一起指定的redis连接参数应该是生效了，启动时会提示`[INFO] App - initStaticRedis success`

请问可能是什么原因呢？

**Comment by qiushaocloud** [comment]
您好，大概率还是您设置的签名key不对导致的，site-counter/web-js/.env 里面设置的是用来打包前端js的，不是docker服务运行使用的
，您再看下 README.md 和 docker-compose.yaml，项目要的 .env 文件映射到容器里面是 /root/site-counter/.env


建议您配置 site-counter/web-js/.env 后打包属于您的 qiushaocloud_site_counter.min.js，这样您在前端时候就不用配置 qiushaocloud_sitecounter_api_host、QIUSHAOCLOUD_SITE_COUNTER_API_SIGN_SECRET_KEY 了，因为打包出来的js是根据这个文件配置的域名和签名密钥打包的

您可以用这个测试demo的代码测试您的域名和签名key: https://githubcdn.qiushaocloud.top/gh/qiushaocloud/cdn-static@master/blog/qiushaocloud-site-counter-test-demo.html
