### ISSUE TITLE
生成js过程中.env文件不起作用

### ISSUE THREAD

**Issue by LittleHeroZZZX** [qiushaocloud/site-counter#2]
根据指引使用`npm run build-dist `命令打包js文件，`web-js/.env`中配置的两个字段并没有正确生效，控制台输出信息显示使用的是默认的配置：

```
YOUR_SERVER_HOST: www.qiushaocloud.top 
API_SIGN_SECRET_KEY: QIU_SHAO_CLOUD_SECRET_KEY
```
在打包命令后增加参数`npm run build-dist <host> <key>`可以解决该问题。

**Comment by LittleHeroZZZX** [comment]
`build-dist`的工作目录问题，已提交修复的pr：https://github.com/qiushaocloud/site-counter/pull/3

**Comment by qiushaocloud** [comment]
已经合并代码
